In [13]:
import numpy as np
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array

In [14]:
x2

array([[2, 5, 3, 1],
       [2, 0, 7, 3],
       [6, 2, 7, 7]])

In [15]:
x2_sub_copy = x2[:2,:2].copy()

In [16]:
print(x2_sub_copy)
x2_sub_copy[0,0] = 50000
print(x2_sub_copy)
print(x2)

[[2 5]
 [2 0]]
[[50000     5]
 [    2     0]]
[[2 5 3 1]
 [2 0 7 3]
 [6 2 7 7]]


In [17]:
x2_sub_copy = x2[:2,:2]

In [18]:
print(x2_sub_copy)
x2_sub_copy[0,0] = 50000
print(x2_sub_copy)
#THIS IS WHY WE USE .COPY()!!! JEEEZ
print(x2)

[[2 5]
 [2 0]]
[[50000     5]
 [    2     0]]
[[50000     5     3     1]
 [    2     0     7     3]
 [    6     2     7     7]]


https://jakevdp.github.io/PythonDataScienceHandbook/02.03-computation-on-arrays-ufuncs.html